---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create docker container
      community.docker.docker_container:
        name: ubuntu
        image: geerlingguy/docker-ubuntu2204-ansible
        command: /sbin/init
        privileged: true
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:rw

    - name: Add container to inventory
      ansible.builtin.add_host:
        name: ubuntu
        ansible_connection: community.docker.docker