# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|


  config.vm.box = "ubuntu/jammy64"


  config.vm.network "private_network", ip: "192.168.56.11"

  
  config.vm.synced_folder ".", "/vagrant", disabled: true


  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  vb.name = "debian_wopress"
  vb.gui = true
  vb.customize [ "modifyvm", :id, "--uart1", "off" ]
  vb.customize [ "modifyvm", :id, "--uart2", "off" ]     
  vb.customize [ "modifyvm", :id, "--uart3", "off" ]
  vb.customize [ "modifyvm", :id, "--uart4", "off" ]


  end

end
